// frontend/src/routes/login/+page.svelte
<!--
  SPDX-License-Identifier: LicenseRef-DSL-1.0
  Deferred Source License (DSL)
  Pacer, Copyright (c) 2026 YouSysAdmin
-->

<script>
  import { auth } from "$lib/api.js";
  import { goto } from "$app/navigation";
  import { page } from "$app/state";

  let email = $state("");
  let password = $state("");
  let loading = $state(false);
  let error = $state(null);
  let info = $state(null);

  // Where to send the user after a successful login. Falls back to
  // the dashboard root when no `next=` param was carried in.
  function nextTarget() {
    const n = page.url.searchParams.get("next");
    if (!n || !n.startsWith("/")) return "/";
    if (n === "/login") return "/";
    return n;
  }

  // OIDC callback redirects back here with ?err=<code> on failure.
  function ssoErrorMessage(code) {
    switch (code) {
      case "sso_idp_error":      return "The identity provider rejected the sign-in.";
      case "sso_state_missing":  return "Sign-in session expired. Please try again.";
      case "sso_token_invalid":  return "Could not verify the identity-provider response.";
      case "sso_bad_callback":   return "Malformed callback from the identity provider.";
      case "sso_access_denied":  return "Access denied for this account.";
      default:                   return null;
    }
  }

  async function submit(e) {
    e.preventDefault();
    error = null;
    loading = true;
    try {
      await auth.login(email.trim(), password);
      goto(nextTarget());
    } catch (err) {
      error = err.message;
    } finally {
      loading = false;
    }
  }

  function startOIDC() {
    // Full-page navigation: SSO flow needs the browser to follow the
    // 302 to the IdP and back.
    window.location.href = "/api/auth/oidc/start";
  }

  $effect(() => {
    const errCode = page.url.searchParams.get("err");
    if (errCode) error = ssoErrorMessage(errCode);

    auth.me()
      .then((r) => {
        if (r && r.auth_disabled) goto("/");
        else if (r && r.user) goto(nextTarget());
      })
      .catch(() => {});

    auth.info()
      .then((r) => { info = r; })
      .catch(() => {});
  });
</script>

<div class="login-page">
  <div class="login-card">
    <div class="login-brand">
      <img src="/logo/wordmark.svg" alt="Pacer" />
    </div>

    <h2>Sign in</h2>

    {#if error}<div class="banner err">{error}</div>{/if}

    {#if info && info.oidc_enabled}
      <button class="btn primary sso" type="button" onclick={startOIDC}>
        Sign in with {info.oidc_label || "SSO"}
      </button>
    {/if}

    {#if info && info.local_enabled}
      {#if info.oidc_enabled}<div class="divider"><span>or</span></div>{/if}
      <form onsubmit={submit}>
        <div class="field">
          <label for="email">Email</label>
          <input
            id="email"
            class="input"
            type="email"
            bind:value={email}
            placeholder="ops@example.com"
            autocomplete="username"
            required
          />
        </div>
        <div class="field">
          <label for="password">Password</label>
          <input
            id="password"
            class="input"
            type="password"
            bind:value={password}
            autocomplete="current-password"
            required
          />
        </div>
        <button class="btn primary" type="submit" disabled={loading}>
          {loading ? "signing in..." : "sign in"}
        </button>
      </form>
    {/if}

    {#if info && !info.local_enabled && !info.oidc_enabled && !info.auth_disabled}
      <p class="muted">No sign-in method is configured. Check <code>auth.local</code> or <code>auth.oidc</code> in your YAML.</p>
    {/if}
  </div>
</div>

<style>
  .login-page {
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 40px 20px;
    background: var(--bg-0);
  }
  .login-card {
    width: 100%;
    max-width: 380px;
    background: var(--bg-2);
    border: 1px solid var(--line-2);
    border-radius: var(--r-md);
    padding: 28px 32px 32px;
  }
  .login-brand {
    display: flex;
    align-items: center;
    gap: 10px;
    color: var(--fg-0);
    font-size: 14px;
    margin-bottom: 24px;
    padding-bottom: 18px;
    border-bottom: 1px solid var(--line-1);
  }
  .login-brand img { height: 36px; width: auto; display: block; }
  .login-card h2 {
    font-size: 20px;
    margin: 0 0 18px;
    color: var(--fg-0);
    font-weight: 500;
  }
  .login-card .btn { width: 100%; margin-top: 8px; }
  .login-card .btn.sso { margin-top: 0; }
  .divider {
    display: flex;
    align-items: center;
    gap: 10px;
    margin: 18px 0;
    color: var(--fg-3);
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.08em;
  }
  .divider::before, .divider::after {
    content: "";
    flex: 1;
    height: 1px;
    background: var(--line-1);
  }
  .muted { color: var(--fg-3); font-size: 13px; }
</style>

// frontend/src/views/login/Login.vue
<script setup lang="ts">
// SPDX-License-Identifier: LicenseRef-DSL-1.0
// Deferred Source License (DSL)
// Pacer, Copyright (c) 2026 YouSysAdmin

// Sign in: local email + password and/or OIDC, driven by what
// GET /api/auth/info says is configured.
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { auth } from '@/api'
import AuthPage from '@/components/AuthPage.vue'
import FormField from '@/components/FormField.vue'
import Notice from '@/components/Notice.vue'

interface AuthInfo {
  local_enabled?: boolean
  oidc_enabled?: boolean
  oidc_label?: string
  auth_disabled?: boolean
}

const route = useRoute()
const router = useRouter()

const email = ref('')
const password = ref('')
const loading = ref(false)
const error = ref<string | null>(null)
const info = ref<AuthInfo | null>(null)

// Where to send the user after a successful login. Falls back to
// the dashboard root when no `next=` param was carried in.
function nextTarget(): string {
  const n = route.query.next
  if (typeof n !== 'string' || !n.startsWith('/')) return '/'
  if (n === '/login') return '/'
  return n
}

// OIDC callback redirects back here with ?err=<code> on failure.
function ssoErrorMessage(code: string): string | null {
  switch (code) {
    case 'sso_idp_error':
      return 'The identity provider rejected the sign-in.'
    case 'sso_state_missing':
      return 'Sign-in session expired. Please try again.'
    case 'sso_token_invalid':
      return 'Could not verify the identity-provider response.'
    case 'sso_bad_callback':
      return 'Malformed callback from the identity provider.'
    case 'sso_access_denied':
      return 'Access denied for this account.'
    default:
      return null
  }
}

async function submit() {
  error.value = null
  loading.value = true
  try {
    await auth.login(email.value.trim(), password.value)
    router.push(nextTarget())
  } catch (err) {
    error.value = (err as Error).message
  } finally {
    loading.value = false
  }
}

function startOIDC() {
  // Full-page navigation: SSO flow needs the browser to follow the
  // 302 to the IdP and back.
  window.location.href = '/api/auth/oidc/start'
}

onMounted(() => {
  const errCode = route.query.err
  if (typeof errCode === 'string') error.value = ssoErrorMessage(errCode)

  // Already signed in (or auth off entirely): nothing to ask.
  auth
    .me()
    .then((r) => {
      const me = r as { auth_disabled?: boolean; user?: unknown } | null
      if (me?.auth_disabled) router.push('/')
      else if (me?.user) router.push(nextTarget())
    })
    .catch(() => {})

  auth
    .info()
    .then((r) => {
      info.value = r as AuthInfo
    })
    .catch(() => {})
})
</script>

<template>
  <AuthPage title="Sign in">
    <Notice v-if="error" kind="danger" class="login-error">{{ error }}</Notice>

    <button
      v-if="info?.oidc_enabled"
      class="btn btn-primary btn-block"
      type="button"
      @click="startOIDC"
    >
      Sign in with {{ info?.oidc_label || 'SSO' }}
    </button>

    <template v-if="info?.local_enabled">
      <div v-if="info?.oidc_enabled" class="auth-or"><span>or</span></div>
      <form class="auth-form" @submit.prevent="submit">
        <FormField label="Email">
          <input
            v-model="email"
            class="form-input"
            type="email"
            placeholder="ops@example.com"
            autocomplete="username"
            required
          />
        </FormField>
        <FormField label="Password">
          <input
            v-model="password"
            class="form-input"
            type="password"
            autocomplete="current-password"
            required
          />
        </FormField>
        <button class="btn btn-primary btn-block" type="submit" :disabled="loading">
          {{ loading ? 'Signing in...' : 'Sign in' }}
        </button>
      </form>
    </template>

    <p
      v-if="info && !info.local_enabled && !info.oidc_enabled && !info.auth_disabled"
      class="auth-note"
    >
      No sign-in method is configured. Check <code>auth.local</code> or <code>auth.oidc</code> in
      your YAML.
    </p>
  </AuthPage>
</template>

<style scoped>
.login-error {
  margin-bottom: 14px;
}
</style>
